### ISSUE TITLE
TaskRole needs AWSAppMeshEnvoyAccess policy

### ISSUE THREAD

**Issue by Y0Username** [subfuzion/enable-appmesh#2]
https://github.com/subfuzion/enable-appmesh/blob/5f374ca63da812d39f2bb02fbe5f7cff32bf1d6b/cdk/lib/mesh-demo-stack.ts#L148-L151

This list needs `ManagedPolicy.fromAwsManagedPolicyName("AWSAppMeshEnvoyAccess")`. Refer https://github.com/aws/aws-app-mesh-roadmap/issues/80 for context.

**Comment by subfuzion** [comment]
Thanks Yathish!
